### ISSUE TITLE
publish campus events on app

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2024Fall/EventAppDemoExample#1]
**User Story**:
Rami, as a student who loves attending campus events, want to see the events displayed on the app, so that he doesn’t need to go out of his way to find events and he can just open the app.

- User (Persona): Rami, who really enjoys campus events to meet more people
- Feature (app is going implement): the app needs to display events
- Business value: the user doesn’t need to go out of his way to find events on campus

**Tasks**:

- [x] Creating an event object
- [x] Design the frontend (creating a view for event)
- [x] Connecting the object (from backend) to the view (frontend)
- [x] Testing
- [x] ? Deployment
- [x] ? Refactoring

**Acceptance Tests**

- All the events should be displayed on the app
- If no events in the database, the app should show a message about empty event.
- If the database is updated, the app will updated automatically. (If the database is updated, the app needs to be refreshed manually to show the updates.)
- No crash at any circumstances.

**Acceptance Criteria**

- The view will only work on Android
- The view will only work when the database does not change
- The view will only be valid when the phone is on vertical view
